Feature/UI tests
jenkinsci/junit-plugin pull request #342
Opened 2022-01-20 22:28 UTC by NikolasFunction

Added ui tests for the junit plugin.
https://issues.jenkins.io/browse/JENKINS-67276

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-01-21 15:59 UTC, NikolasFunction commented
@jglick @kohsuke @timja 

Could one of you please add @uhafner as a PR reviewer?
It seems he doesn't have rights for this action. Thanks!

2022-02-17 23:08 UTC, jtnord commented
What is the reasoning to do this here?
UI testing will be brittle with changes in Jenkins core so the BOM will likely be failing regularly for weeklies, and or versions held back from the BOM for some lines.

2022-02-17 23:30 UTC, jglick commented
Note that this will complicate infrastructure somewhat. https://github.com/jenkinsci/plugin-compat-tester/pull/249

2022-02-18 07:59 UTC, uhafner commented
> What is the reasoning to do this here?

I think UI tests belong to a plugin like unit and integration tests (the idea is from @olivergondza, see https://github.com/jenkinsci/acceptance-test-harness/pull/556 for details). After contributing to ATH for several years now I made the observation that nobody is actually looking at UI tests that are located somewhere else. So it makes sense to have them in the plugin. Then we see if a new feature breaks an existing feature (on the UI side) or if an upgrade to a more recent core version breaks the UI.

Additionally, JUnit plugin uses integration tests with HTMLUnit which does not support modern JS frameworks (see #272, #286) . So it makes sense to remove those tests in favor of real UI tests. 

> UI testing will be brittle with changes in Jenkins core so the Jenkins tools BOM will likely be failing regularly for weeklies, and or versions held back from the BOM for some lines.

Why should that be a problem? If the tests will break then something in the UI is wrong. That means we should fix it.

2022-02-18 08:04 UTC, uhafner commented
> Note that this will complicate infrastructure somewhat. [jenkinsci/plugin-compat-tester#249](https://github.com/jenkinsci/plugin-compat-tester/pull/249)

I haven't looked in detail at those changes but I would assume that we would have two alternatives: a single module plugin and a multi-module plugin. So the `ifWarnings` blocks should be actually `ifMultiModule` blocks. 

Would it be possible to just use the plugin module in those tests and ignore the other ones?

2022-02-18 08:14 UTC, timja commented
As Ulli said the critical reason for this is modern JS frameworks don't work with HTMLUnit 😢

2022-02-21 00:31 UTC, uhafner requested changes
See comments in https://github.com/jenkinsci/junit-plugin/pull/355#pullrequestreview-888093560. 

GitHub is unable to render this PR in my browser.

2022-02-21 11:21 UTC, jtnord reviewed
I forgot to finish my review :(

2022-04-23 11:27 UTC, uhafner commented
@NikolasFunction @Tjuri Are you still planning to update this PR? The longer you are waiting the more merge conflicts will occur...

2026-06-10 20:46 UTC, timja commented
Principle is good but this has been abandoned

2026-06-10 20:46 UTC, closed without merging